import json
import pathlib
from typing import Any, Dict

# Best-effort mapping from user-facing labels to AE workingSpace strings.
# AE silently raises if the profile name doesn't match the installed library,
# so the JSX wraps the assignment in try/catch.
_COLOR_SPACE_MAP = {
    "sRGB": "sRGB IEC61966-2.1",
    "Rec. 709": "Rec.709 Gamma 2.4",
    "ACES": "ACES2065-1",
}


def create_project_folders(project_path: pathlib.Path):
    """Creates the standard folder structure for an After Effects project."""
    folders = [
        "project",
        "footage/video",
        "footage/audio",
        "footage/renders",
        "assets/images",
        "assets/fonts",
        "assets/documents",
        "exports/drafts",
        "exports/final",
    ]
    for folder in folders:
        (project_path / folder).mkdir(parents=True, exist_ok=True)


def generate_jsx(project_path: pathlib.Path, project_name: str, config: Dict[str, Any]) -> pathlib.Path:
    """Generates an ExtendScript .jsx file with the project configuration."""
    width_str, height_str = config["resolution"].split("×")
    width = int(width_str)
    height = int(height_str)
    fps = int(config["fps"])
    duration = int(config["duration"])

    save_path = (project_path / "project" / f"{project_name}.aep").resolve()
    name_literal = json.dumps(project_name)
    working_space_literal = json.dumps(_COLOR_SPACE_MAP.get(config["color_space"], ""))
    save_path_literal = json.dumps(str(save_path))

    jsx_content = f"""// Auto-generated by aeset — do not edit manually
var projectName   = {name_literal};
var width         = {width};
var height        = {height};
var fps           = {fps};
var duration      = {duration};
var workingSpace  = {working_space_literal};
var savePath      = {save_path_literal};

app.beginUndoGroup("Scaffold Project");

if (!app.project || app.project.file !== null || app.project.items.length > 0) {{
    app.newProject();
}}

var compFolder    = app.project.items.addFolder("_COMPS");
var footageFolder = app.project.items.addFolder("_FOOTAGE");
var assetsFolder  = app.project.items.addFolder("_ASSETS");
var audioFolder   = app.project.items.addFolder("_AUDIO");

var comp = app.project.items.addComp(
    projectName,
    width,
    height,
    1.0,
    duration,
    fps
);
comp.parentFolder = compFolder;

if (workingSpace.length > 0) {{
    try {{ app.project.workingSpace = workingSpace; }} catch (e) {{}}
}}

comp.openInViewer();
app.endUndoGroup();

try {{
    var aepFile = new File(savePath);
    app.project.save(aepFile);
}} catch (e) {{
    try {{ app.project.save(); }} catch (err) {{}}
}}
"""
    jsx_path = project_path / "project" / "setup.jsx"
    jsx_path.write_text(jsx_content)
    return jsx_path


def generate_readme(project_path: pathlib.Path, project_name: str, config: Dict[str, Any]):
    """Generates a README.md for the project with metadata."""
    readme_content = f"""# {project_name}

**Project Type:** {config["type"]}
**Resolution:** {config["resolution"]}
**Frame Rate:** {config["fps"]} fps
**Duration:** {config["duration"]} seconds
**Color Space:** {config["color_space"]}
**Created:** {config["date"]}

---
Auto-generated by aeset.
"""
    (project_path / "README.md").write_text(readme_content)

