// Auto-generated by aeset — do not edit manually
var projectName = "test-project";
var width       = 1920;
var height      = 1080;
var fps         = 30;
var duration    = 70;

app.project.save();

var comp = app.project.items.addComp(
    projectName,
    width,
    height,
    1.0,
    duration,
    fps
);

comp.openInViewer();
app.project.save();
